# generated by datamodel-codegen:
#   filename:  project.yaml
#   timestamp: 2022-09-22T21:18:02+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Extra, Field


class ProjectId(BaseModel):
    """
    See source code for the fields' description.
    """

    class Config:
        extra = Extra.allow
        allow_mutation = False

    __root__: UUID = Field(
        ...,
        description="Unique ID for a Hex project",
        regex="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ABab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    )


class ProjectRunStatus(Enum):
    """
    Current status of a project run
    """

    pending = "PENDING"
    running = "RUNNING"
    errored = "ERRORED"
    completed = "COMPLETED"
    killed = "KILLED"
    unabletoallocatekernel = "UNABLE_TO_ALLOCATE_KERNEL"


class RunId(BaseModel):
    """
    See source code for the fields' description.
    """

    class Config:
        extra = Extra.allow
        allow_mutation = False

    __root__: UUID = Field(
        ...,
        description="Unique ID for a run of a Hex project",
        regex="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89ABab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$",
    )


class RunStatusUrl(BaseModel):
    """
    See source code for the fields' description.
    """

    class Config:
        extra = Extra.allow
        allow_mutation = False

    __root__: str = Field(
        ..., description="URL to query the status of the project run via the Hex API"
    )


class RunUrl(BaseModel):
    """
    See source code for the fields' description.
    """

    class Config:
        extra = Extra.allow
        allow_mutation = False

    __root__: str = Field(
        ...,
        description="URL to view the current progress of the project run in the Hex UI",
    )


class TraceId(BaseModel):
    """
    See source code for the fields' description.
    """

    class Config:
        extra = Extra.allow
        allow_mutation = False

    __root__: str = Field(
        ...,
        description=(
            "Hex trace ID to identify an API request. Provide this value to hex support"
            " with any API issues you encounter"
        ),
    )


class ProjectStatusResponsePayload(BaseModel):
    """
    See source code for the fields' description.

    Response format returned by the getRunStatus endpoint
    """

    class Config:
        extra = Extra.allow
        extra = Extra.forbid
        allow_mutation = False

    elapsed_time: float = Field(
        ...,
        alias="elapsedTime",
        description="Total elapsed time for the project run in milliseconds",
    )
    end_time: datetime = Field(
        ...,
        alias="endTime",
        description="UTC timestamp of when the project run finished",
    )
    project_id: ProjectId = Field(..., alias="projectId")
    run_id: RunId = Field(..., alias="runId")
    run_url: RunUrl = Field(..., alias="runUrl")
    start_time: datetime = Field(
        ...,
        alias="startTime",
        description="UTC timestamp of when the project run started",
    )
    status: ProjectRunStatus
    trace_id: TraceId = Field(..., alias="traceId")
